name: redis-ai-java-resources
version: "3"
services:
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
  vecsim:
    image: redis/redis-stack:edge
    ports:
      - "6379:6379"
